---

- name: 1.3.1 Ensure Aide is installed
  yum:
    name: aide
    state: present

- name: 1.3.2 Ensure filesystem integrity is regularly checked
  cron:
    name: run AIDE check
    minute: 5
    hour: 4
    weekday: 0
    user: root
    job: /usr/sbin/aide --check
  when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]

