---

- name: 1.3.1 Ensure Aide is installed
  yum:
    name: aide
    state: present

- name: 1.3.2 Ensure filesystem integrity is regularly checked
  service: 
    name: aidecheck.service
    enabled: yes
    state: started

- name: 1.3.2 Ensure aidecheck.timer is running
  service: 
    name: aidecheck.timer
    enabled: yes
    state: started

