---

- name: CIS 6.1.2 | test for existence /etc/passwd
  stat:
    path: /etc/passwd
  register: file_exists

- name: CIS 6.1.2 | ensure permissions on /etc/passwd
  file:
    path: /etc/passwd
    mode: 0644
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 6.1.3 | test for existence /etc/passwd-
  stat:
    path: /etc/passwd-
  register: file_exists

- name: CIS 6.1.3 | ensure permissions on /etc/passwd-
  file:
    path: /etc/passwd-
    mode: 0644
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 6.1.4 | test for existence /etc/shadow
  stat:
    path: /etc/shadow
  register: file_exists

- name: CIS 6.1.4 | ensure permissions on /etc/shadow
  file:
    path: /etc/shadow
    mode: 0000
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 6.1.5 | test for existence /etc/shadow-
  stat:
    path: /etc/shadow-
  register: file_exists

- name: CIS 6.1.5 | ensure permissions on /etc/shadow-
  file:
    path: /etc/shadow-
    mode: 0000
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 6.1.6 | test for existence /etc/gshadow
  stat:
    path: /etc/gshadow
  register: file_exists

- name: CIS 6.1.6 | ensure permissions on /etc/gshadow
  file:
    path: /etc/gshadow
    mode: 0000
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 6.1.7 | test for existence /etc/gshadow-
  stat:
    path: /etc/gshadow-
  register: file_exists

- name: CIS 6.1.7 | ensure permissions on /etc/gshadow-
  file:
    path: /etc/gshadow-
    mode: 0000
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 6.1.8 | test for existence /etc/group
  stat:
    path: /etc/group
  register: file_exists

- name: CIS 6.1.8 | ensure permissions on /etc/group
  file:
    path: /etc/group
    mode: 0644
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists

- name: CIS 6.1.9 | test for existence /etc/group-
  stat:
    path: /etc/group-
  register: file_exists

- name: CIS 6.1.9 | ensure permissions on /etc/group-
  file:
    path: /etc/group-
    mode: 0644
    owner: '0'
    group: '0'
  when: file_exists.stat is defined and file_exists.stat.exists





