---

- name: CIS 5.2.1 | ensure permissions on /etc/ssh/sshd_config
  file:
    path: /etc/ssh/sshd_config
    group: '0'
    owner: '0'
    mode: '0600'

- name: CIS 5.2.3 | find ssh private keys
  find:
    paths: /etc/ssh/
    patterns: ^.*_key$
    use_regex: true
  register: files_found

- name: CIS 5.2.3 | set permissions on ssh private key files
  file:
    path: '{{ item.path }}'
    mode: '0640'
  with_items:
  - '{{ files_found.files }}'

- name: CIS 5.2.4 | find ssh public keys
  find:
    paths: /etc/ssh/
    patterns: ^.*.pub$
    use_regex: true
  register: files_found

- name: CIS 5.2.4 | set permissions on ssh public key files
  file:
    path: '{{ item.path }}'
    mode: '0644'
  with_items:
  - '{{ files_found.files }}'

- name: CIS 5.2.16 Ensure SSH MaxAuthTries is set to 4 or less
  lineinfile:
    path: /etc/ssh/sshd_config
    create: false
    regexp: (?i)^\s*MaxSessions\s+
    state: absent
  check_mode: true
  changed_when: false
  register: dupes

- name: CIS 5.2.16 Ensure SSH MaxAuthTries is set to 4 or less
  lineinfile:
    path: /etc/ssh/sshd_config
    create: false
    regexp: (?i)^\s*MaxSessions\s+
    state: absent
  when: dupes.found is defined and dupes.found > 1

- name: CIS 5.2.16 Ensure SSH MaxAuthTries is set to 4 or less
  lineinfile:
    path: /etc/ssh/sshd_config
    create: true
    regexp: (?i)^\s*MaxSessions\s+
    line: MaxSessions {{ var_sshd_max_sessions }}
    state: present
    insertbefore: ^[#\s]*Match
    validate: /usr/sbin/sshd -t -f %s
  when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]

- name: Ensure SSH MaxStartups is configured
  lineinfile:
    path: /etc/ssh/sshd_config
    create: true
    regexp: (?i)^\s*MaxStartups\s+
    line: MaxStartups {{ var_sshd_set_maxstartups }}
    state: present
    insertbefore: ^[#\s]*Match
    validate: /usr/sbin/sshd -t -f %s

